[build]
  publish = "./"
  command = ""

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/"
  to = "/html/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/html/index.html"
  status = 200

# Add custom headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
